### PR TITLE
Implement support for JWT algos

### PR DESCRIPTION
**Pull request by ccamel**
Comes with https://github.com/prest/config/pull/20.
See https://github.com/prest/prest/issues/286.

### CODE REVIEW

**Review by felipeweb — APPROVED** [review]
LGTM

**Review by avelino — APPROVED** [review]
Lgtm

**Review by felipeweb — CHANGES_REQUESTED** [review]
@ccamel  after merge config your tests are broken

**Comment by ccamel** [comment]
@felipeweb Thanks. I'm looking at it.

**Comment by ccamel** [comment]
@felipeweb I succeeded in fixing the tests for the target `go-1.8`. But the sources doesn't compile for the target `go-1.7`. The library  [jmoiron/sqlx](https://github.com/jmoiron/sqlx) used by `pREST` makes use of the [ComumnType]( https://tip.golang.org/pkg/database/sql/#ColumnType) type which has been introduced, from my understanding, in go 1.8.

An issue has been reported in the project: jmoiron/sqlx/issues/393.

**Comment by ccamel** [comment]
Should we go with  Go 1.8 and above ?

**Comment by felipeweb** [comment]
@ccamel  just merge master into your branch to remove Go 1.7 and add newest versions on travis file

**Comment by ccamel** [comment]
@felipeweb It worked ! :tada: Thanks.

**Review by felipeweb — APPROVED** [review]

**Pull request merged**
